version: '3.7'
services:
  web:
    image: etherpad/etherpad:1.8.4
    env_file: etherpad.env
    ports:
    - "9001:9001"
    depends_on:
    - database
    restart: on-failure
    volumes:
    - ./scripts:/scripts:z
    command: sh -c '/scripts/entrypoint.sh'
  database:
    image: mariadb:10.5.5
    env_file: etherpad.env
    # TODO: Don't expose database ports once we're done.
    ports:
    - "3306:3306"
    restart: on-failure
    volumes:
    - ./data:/var/lib/mysql:z
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
